//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using WebApiApplication.viewModel;

//#nullable disable

//namespace WebApiApplication.Migrations
//{
//    [DbContext(typeof(EmployeeDbContext))]
//    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.8")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//            modelBuilder.Entity("WebApiApplication.viewModel.AppraisalDetails", b =>
//                {
//                    b.Property<Guid>("EmployeeNumber")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Action")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("AnyIssue")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("BehaviouralPercent")
//                        .HasColumnType("int");

//                    b.Property<string>("CommentsToSupport")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("CompletedPercent")
//                        .HasColumnType("int");

//                    b.Property<string>("ExceptionallyHighPerformer")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("HappinessPercent")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("NineGridScoreDescription")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("NumberOfGoals")
//                        .HasColumnType("int");

//                    b.Property<int>("PerformancePercent")
//                        .HasColumnType("int");

//                    b.Property<string>("ProjectManagerFeedback")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("QuarterYear")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Reviewer")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("EmployeeNumber");

//                    b.ToTable("AppraisalDetails");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.CheckList", b =>
//                {
//                    b.Property<Guid>("EmployeeId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<int>("Achievable")
//                        .HasColumnType("int");

//                    b.Property<int>("Achieved")
//                        .HasColumnType("int");

//                    b.Property<string>("CType")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("QuarterYear")
//                        .HasColumnType("datetime2");

//                    b.HasKey("EmployeeId");

//                    b.ToTable("checkLists");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.EmployeeGoalMonthWise", b =>
//                {
//                    b.Property<int>("CompletedPercent")
//                        .HasColumnType("int");

//                    b.Property<string>("EmployeeComments")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("EmployeeGoalObjective")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("SupervisorComments")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("quarterName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.ToTable("EmployeeGoalMonthWise");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.EmployeeGoalObjectives", b =>
//                {
//                    b.Property<string>("ActionStatus")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("CompletedPercentage")
//                        .HasColumnType("int");

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("EmployeeQuarterlyGoalName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Objective")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Review")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.ToTable("EmployeeGoalObjectives");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.EmployeeQuarterlyGoals", b =>
//                {
//                    b.Property<Guid>("EmployeeId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("GoalName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("QuarterName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Weightage")
//                        .HasColumnType("int");

//                    b.HasKey("EmployeeId");

//                    b.ToTable("EmployeeQuarterlyGoals");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.Employees", b =>
//                {
//                    b.Property<Guid>("EmployeeId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<int>("Contact")
//                        .HasColumnType("int");

//                    b.Property<string>("Department")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Designation")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("JoiningDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("SupervisiorName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("EmployeeId");

//                    b.ToTable("Employees");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.FinancialYear", b =>
//                {
//                    b.Property<string>("FinancialYearName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("FromDate")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("ToDate")
//                        .HasColumnType("datetime2");

//                    b.ToTable("financialYears");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.Goals", b =>
//                {
//                    b.Property<string>("GoalName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("GoalType")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.ToTable("Goals");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.NineGridDetails", b =>
//                {
//                    b.Property<int>("Choice")
//                        .HasColumnType("int");

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.ToTable("NineGridDetails");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.OnTheMoment", b =>
//                {
//                    b.Property<string>("Action")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Comments")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid>("FromEmployeeNumber")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<DateTime>("RequestedDate")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("RespondedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<Guid>("ToEmployeeNumber")
//                        .HasColumnType("uniqueidentifier");

//                    b.ToTable("OnTheMoment");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.PromotionData", b =>
//                {
//                    b.Property<Guid>("EmployeeId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<DateTime>("LastPromotionDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("PromotionComments")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ReadyForPromotion")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("EmployeeId");

//                    b.ToTable("PromotionData");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.QuarterDetails", b =>
//                {
//                    b.Property<string>("MonthName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("MonthNumber")
//                        .HasColumnType("int");

//                    b.Property<string>("QuarterFinancialYearName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.ToTable("QuarterDetails");
//                });

//            modelBuilder.Entity("WebApiApplication.viewModel.QuarterFinancialYear", b =>
//                {
//                    b.Property<string>("FinancialYearName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("FromDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("QuarterFinancialYearName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("ToDate")
//                        .HasColumnType("datetime2");

//                    b.ToTable("QuarterFinancialYear");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
